cmd = ['Sqlcmd -i "C:\\Coding\\repl\\SQL\\Repl-PL.sql" -S "TP-PL-CDB01" -o "C:\\Coding\\repl\\Results\\Result_PL1.csv" -s ";"',
'Sqlcmd -i "C:\\Coding\\repl\\SQL\\Repl-PL.sql" -S "TP-PL-CDB02" -o "C:\\Coding\\repl\\Results\\Result_PL2.csv" -s ";"',
'Sqlcmd -i "C:\\Coding\\repl\\SQL\\Repl-PL.sql" -S "TP-PL-CDB03" -o "C:\\Coding\\repl\\Results\\Result_PL3.csv" -s ";"',
'Sqlcmd -i "C:\\Coding\\repl\\SQL\\Repl-PL.sql" -S "TP-PL-CDB04" -o "C:\\Coding\\repl\\Results\\Result_PL4.csv" -s ";"',
'Sqlcmd -i "C:\\Coding\\repl\\SQL\\Repl-PL.sql" -S "TP-PL-CDB05" -o "C:\\Coding\\repl\\Results\\Result_PL5.csv" -s ";"',
'Sqlcmd -i "C:\\Coding\\repl\\SQL\\Repl-PL.sql" -S "TP-PL-CDB06" -o "C:\\Coding\\repl\\Results\\Result_PL6.csv" -s ";"',
'Sqlcmd -i "C:\\Coding\\repl\\SQL\\Repl-HU.sql" -S "TP-IN-CDB01" -o "C:\\Coding\\repl\\Results\\Result_HU.csv" -s ";"',
'Sqlcmd -i "C:\\Coding\\repl\\SQL\\Repl-HR.sql" -S "TP-IN-CDB01" -o "C:\\Coding\\repl\\Results\\Result_HR.csv" -s ";" ',
'Sqlcmd -i "C:\\Coding\\repl\\SQL\\Repl-CZ.sql" -S "TP-IN-CDB02" -o "C:\\Coding\\repl\\Results\\Result_CZ.csv" -s ";"',
'Sqlcmd -i "C:\\Coding\\repl\\SQL\\Repl-SI.sql" -S "TP-IN-CDB02" -o "C:\\Coding\\repl\\Results\\Result_SI.csv" -s ";"',
'Sqlcmd -i "C:\\Coding\\repl\\SQL\\Repl-EE.sql" -S "TP-IN-CDB03" -o "C:\\Coding\\repl\\Results\\Result_EE.csv" -s ";"',
'Sqlcmd -i "C:\\Coding\\repl\\SQL\\Repl-LT.sql" -S "TP-IN-CDB03" -o "C:\\Coding\\repl\\Results\\Result_LT.csv" -s ";"',
'Sqlcmd -i "C:\\Coding\\repl\\SQL\\Repl-LV.sql" -S "TP-IN-CDB03" -o "C:\\Coding\\repl\\Results\\Result_LV.csv" -s ";"',
'Sqlcmd -i "C:\\Coding\\repl\\SQL\\Repl-SK.sql" -S "TP-IN-CDB03" -o "C:\\Coding\\repl\\Results\\Result_SK.csv" -s ";"',
'Sqlcmd -i "C:\\Coding\\repl\\SQL\\Repl-BG.sql" -S "TP-IN-CDB04" -o "C:\\Coding\\repl\\Results\\Result_BG.csv" -s ";"',
'Sqlcmd -i "C:\\Coding\\repl\\SQL\\Repl-IT.sql" -S "TP-IN-CDB04" -o "C:\\Coding\\repl\\Results\\Result_IT.csv" -s ";"',
'Sqlcmd -i "C:\\Coding\\repl\\SQL\\Repl-RS.sql" -S "TP-IN-CDB04" -o "C:\\Coding\\repl\\Results\\Result_RS.csv" -s ";"',
'Sqlcmd -i "C:\\Coding\\repl\\SQL\\Repl-RO.sql" -S "TP-RO-CDB01" -o "C:\\Coding\\repl\\Results\\Result_RO1.csv" -s ";"',
'Sqlcmd -i "C:\\Coding\\repl\\SQL\\Repl-RO.sql" -S "TP-RO-CDB02" -o "C:\\Coding\\repl\\Results\\Result_RO2.csv" -s ";"']